use crate::harness::*;
use crate::*;
use std::time::Duration;

pub mod basic;
pub mod boot_contract;
pub mod build_steps;
pub mod cache_busting;
pub mod code_execution;
pub mod content;
pub mod dead_links;
pub mod error_detection;
pub mod internal_links;
pub mod livereload;
pub mod mermaid;
pub mod picante_cache;
pub mod protocols;
pub mod sass;
pub mod section_pages;
pub mod static_assets;
pub mod templates;
